map $request_method $timeline_limit_key {
    default   "";
    POST      $binary_remote_addr;
}

limit_req_zone $timeline_limit_key zone=timeline_limit:10m rate=1r/m;

server {
    listen 80;
    server_name srinidhi-portfolio.duckdns.org;
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name srinidhi-portfolio.duckdns.org;

    location /api/timeline_post {
        limit_req zone=timeline_limit nodelay;
        limit_req_status 429;
        proxy_pass http://myportfolio:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass http://myportfolio:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_certificate /etc/letsencrypt/live/srinidhi-portfolio.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/srinidhi-portfolio.duckdns.org/privkey.pem;
}
